package me.kendler.yanik.socket;

public enum ShotlistUpdateType {
    USER_JOINED,
    USER_LEFT,
    COLLABORATION_TYPE_UPDATED,
    COLLABORATION_DELETED,
    PRESENT_COLLABORATORS,
    SHOT_ATTRIBUTE_UPDATED,
    SHOT_ADDED,
    SHOT_UPDATED,
    SHOT_DELETED,
    SCENE_ATTRIBUTE_UPDATED,
    SCENE_ADDED,
    SCENE_UPDATED,
    SCENE_DELETED,
    SCENE_SELECT_OPTION_CREATED,
    SHOT_SELECT_OPTION_CREATED,
    SHOTLIST_OPTIONS_UPDATED,
    COLLABORATOR_CELL_SELECTED
}