# AI
server {
    listen 8080;
    server_name _;

    port_in_redirect off;
    absolute_redirect off;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
        proxy_redirect off;
        proxy_bind $host:80;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Host $http_host;
    }
}